# PostgreSQL. Versions 8.2 and up are supported.
# Use 'createuser -s postgres' to create a general purpose db (super)user.

development: &default
  adapter: postgresql
  encoding: unicode
  database: app_prototype_development
  username: postgres
  pool: 5
  timeout: 5000

test:
  <<: *default
  database: app_prototype_test
  min_messages: warning
