source 'https://rubygems.org'

# Heroku uses the ruby version to configure your application's runtime.
ruby 'RUBY_VERSION'

gem 'thin'
gem 'rails', '~> 3.2.9'
gem 'slim-rails'
gem 'jquery-rails'
gem 'sorcery'
gem 'cancan'
gem 'simple_form'
gem 'active_attr'
gem 'valid_email'
gem 'pg'
gem 'awesome_print'

group :assets do
  gem 'less-rails'
  gem 'less-rails-bootstrap'
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'therubyracer', platforms: :ruby
end

group :test, :development do
  gem 'rspec-rails', '~> 2.12.0'
  gem 'capybara', github: 'jnicklas/capybara' # Switch from github once issue #882 is resolved.
  gem 'factory_girl_rails'
  gem 'jasminerice'
  gem 'timecop'
  gem 'simplecov'
end

group :development do
  gem 'foreman'
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-jasmine'
  gem 'guard-livereload'
  gem 'rb-fsevent'
  gem 'growl'
end
